name: Bankey
options:
  bundleIdPrefix: com.devmeist3r
  createIntermediateGroups: true
  generateEmptyDirectories: true
  developmentLanguage: en
targets:
  Bankey:
    type: application
    platform: iOS
    deploymentTarget: '15.0'
    sources: [Bankey]
    scheme:
      testTargets:
        - BankeyUnitTests
  BankeyUnitTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: BankeyUnitTests
